version: '3'

services:
  course-go-api:
    container_name: course_go_api
    build: .
    environment:
      COURSE_GO_HOST: 0.0.0.0
      COURSE_GO_PORT: 8080
      COURSE_GO_DB_USER: postgres
      COURSE_GO_DB_PASS: admin
      COURSE_GO_DB_HOST: postgres
      COURSE_GO_DB_PORT: 5432
      COURSE_GO_DB_NAME: course_go
    ports:
      - "8080:8080"
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: course_go
    volumes:
      - postgres_data:/var/lib/postgres
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data: